---
x-airflow-common:
  &airflow-common
  image: ${DOCKERHUB_NAMESPACE}/${DOCKERHUB_REPOSITORY}:latest
  user: "0:0"

  environment: &airflow-common-env
    AIRFLOW__CORE__EXECUTOR: CeleryExecutor
    AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://${METADATA_DATABASE_USERNAME}:${METADATA_DATABASE_PASSWORD}@${POSTGRES_CONN_HOST}:${POSTGRES_CONN_PORT}/${METADATA_DATABASE_NAME}
    AIRFLOW__CELERY__RESULT_BACKEND: db+postgresql://${CELERY_BACKEND_USERNAME}:${CELERY_BACKEND_PASSWORD}@${POSTGRES_CONN_HOST}:${POSTGRES_CONN_PORT}/${CELERY_BACKEND_NAME}
    AIRFLOW__CELERY__BROKER_URL: redis://:@redis:6379/0
    AIRFLOW__CORE__FERNET_KEY: ${FERNET_KEY}
    AIRFLOW__CORE__DAGS_ARE_PAUSED_AT_CREATION: 'true'
    AIRFLOW__CORE__LOAD_EXAMPLES: 'false'
    AIRFLOW__API__AUTH_BACKENDS: 'airflow.api.auth.backend.basic_auth,airflow.api.auth.backend.session'
    AIRFLOW__SCHEDULER__ENABLE_HEALTH_CHECK: 'true'
    AIRFLOW__SCHEDULER__STANDALONE_DAG_PROCESSOR: 'True'

    AIRFLOW_CONN_POSTGRES_DB_YT_ELT: 'postgresql://${ELT_DATABASE_USERNAME}:${ELT_DATABASE_PASSWORD}@${POSTGRES_CONN_HOST}:${POSTGRES_CONN_PORT}/${ELT_DATABASE_NAME}'

    AIRFLOW_VAR_API_KEY: ${API_KEY}
    AIRFLOW_VAR_CHANNEL_HANDLE: ${CHANNEL_HANDLE}

    ELT_DATABASE_NAME: ${ELT_DATABASE_NAME}
    ELT_DATABASE_USERNAME: ${ELT_DATABASE_USERNAME}
    ELT_DATABASE_PASSWORD: ${ELT_DATABASE_PASSWORD}
    POSTGRES_CONN_HOST: ${POSTGRES_CONN_HOST}
    POSTGRES_CONN_PORT: ${POSTGRES_CONN_PORT}

  volumes:
    - ./config:/opt/airflow/config
    - ./dags:/opt/airflow/dags
    - ./data:/opt/airflow/data
    - ./include:/opt/airflow/include
    - airflow-logs:/opt/airflow/logs
    - ./plugins:/opt/airflow/plugins
    - ./tests:/opt/airflow/tests

  depends_on:
    &airflow-common-depends-on
    redis:
      condition: service_healthy
    postgres:
      condition: service_healthy

services:
  postgres:
    container_name: postgres
    image: postgres:13
    environment:
      - POSTGRES_USER=${POSTGRES_CONN_USERNAME}
      - POSTGRES_PASSWORD=${POSTGRES_CONN_PASSWORD}
      - METADATA_DATABASE_NAME=${METADATA_DATABASE_NAME}
      - METADATA_DATABASE_USERNAME=${METADATA_DATABASE_USERNAME}
      - METADATA_DATABASE_PASSWORD=${METADATA_DATABASE_PASSWORD}
      - ELT_DATABASE_NAME=${ELT_DATABASE_NAME}
      - ELT_DATABASE_USERNAME=${ELT_DATABASE_USERNAME}
      - ELT_DATABASE_PASSWORD=${ELT_DATABASE_PASSWORD}
      - CELERY_BACKEND_NAME=${CELERY_BACKEND_NAME}
      - CELERY_BACKEND_USERNAME=${CELERY_BACKEND_USERNAME}
      - CELERY_BACKEND_PASSWORD=${CELERY_BACKEND_PASSWORD}
      - POSTGRES_CONN_HOST=${POSTGRES_CONN_HOST}
      - POSTGRES_CONN_PORT=${POSTGRES_CONN_PORT}
    ports:
      - "5433:5432"
    volumes:
      - postgres-db-volume:/var/lib/postgresql/data
      - ./docker/postgres/init-multiple-databases.sh:/docker-entrypoint-initdb.d/init-multiple-databases.sh
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_CONN_USERNAME:-postgres} -d postgres"]
      interval: 10s
      timeout: 5s
      retries: 30
      start_period: 60s
    restart: always

  redis:
    image: redis:7.2-bookworm
    expose:
      - 6379
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 30s
      retries: 50
      start_period: 30s
    restart: always

  airflow-webserver:
    <<: *airflow-common
    command: webserver
    ports:
      - "8080:8080"
    healthcheck:
      test: ["CMD", "curl", "--fail", "http://localhost:8080/health"]
      interval: 30s
      timeout: 10s
      retries: 20
      start_period: 180s
    restart: always
    depends_on:
      <<: *airflow-common-depends-on
      airflow-init:
        condition: service_completed_successfully

  airflow-scheduler:
    <<: *airflow-common
    command: scheduler
    healthcheck:
      test: ["CMD", "curl", "--fail", "http://localhost:8974/health"]
      interval: 30s
      timeout: 10s
      retries: 20
      start_period: 180s
    restart: always
    depends_on:
      <<: *airflow-common-depends-on
      airflow-init:
        condition: service_completed_successfully

  airflow-dag-processor:
    <<: *airflow-common
    command: dag-processor
    healthcheck:
      test: ["CMD-SHELL", 'airflow jobs check --job-type DagProcessorJob --hostname "$${HOSTNAME}"']
      interval: 30s
      timeout: 10s
      retries: 20
      start_period: 180s
    restart: always
    depends_on:
      <<: *airflow-common-depends-on
      airflow-init:
        condition: service_completed_successfully

  airflow-worker:
    <<: *airflow-common
    command: celery worker
    healthcheck:
      test: ["CMD-SHELL", 'celery --app airflow.providers.celery.executors.celery_executor.app inspect ping -d "celery@$${HOSTNAME}" || celery --app airflow.executors.celery_executor.app inspect ping -d "celery@$${HOSTNAME}"']
      interval: 30s
      timeout: 10s
      retries: 20
      start_period: 180s
    environment:
      <<: *airflow-common-env
      DUMB_INIT_SETSID: "0"
    restart: always
    depends_on:
      <<: *airflow-common-depends-on
      airflow-init:
        condition: service_completed_successfully

  airflow-init:
    <<: *airflow-common
    entrypoint: /bin/bash
    command:
      - -c
      - |
        if [[ -z "${AIRFLOW_UID}" ]]; then
          echo "AIRFLOW_UID not set. Using current user id."
          export AIRFLOW_UID=$$(id -u)
        fi

        echo "Creating Airflow folders..."
        mkdir -p /opt/airflow/{logs,dags,plugins,config,data,include,tests}
        mkdir -p /opt/airflow/logs/scheduler

        echo "Fixing ownership..."
        chown -R "${AIRFLOW_UID}:0" /opt/airflow/{logs,dags,plugins,config,data,include,tests}
        chmod -R 775 /opt/airflow/{logs,dags,plugins,config,data,include,tests}

        echo "Airflow version:"
        /entrypoint airflow version

        echo "Running Airflow DB migration and user creation..."
        /entrypoint airflow db migrate
        /entrypoint airflow users create \
          --username "${_AIRFLOW_WWW_USER_USERNAME:-airflow}" \
          --password "${_AIRFLOW_WWW_USER_PASSWORD:-airflow}" \
          --firstname Airflow \
          --lastname Admin \
          --role Admin \
          --email airflow@example.com || true

        echo "Airflow init completed."
    environment:
      <<: *airflow-common-env
      _AIRFLOW_DB_MIGRATE: 'true'
      _AIRFLOW_WWW_USER_CREATE: 'true'
      _AIRFLOW_WWW_USER_USERNAME: ${_AIRFLOW_WWW_USER_USERNAME:-airflow}
      _AIRFLOW_WWW_USER_PASSWORD: ${_AIRFLOW_WWW_USER_PASSWORD:-airflow}
      _PIP_ADDITIONAL_REQUIREMENTS: ''
    user: "0:0"
    volumes:
      - ./config:/opt/airflow/config
      - ./dags:/opt/airflow/dags
      - ./data:/opt/airflow/data
      - ./include:/opt/airflow/include
      - airflow-logs:/opt/airflow/logs
      - ./plugins:/opt/airflow/plugins
      - ./tests:/opt/airflow/tests

  airflow-cli:
    <<: *airflow-common
    profiles:
      - debug
    environment:
      <<: *airflow-common-env
      CONNECTION_CHECK_MAX_COUNT: "0"
    command:
      - bash
      - -c
      - airflow

volumes:
  postgres-db-volume:
  airflow-logs: