name: CI-CD Pipeline

on:
  push:
    branches:
      - main
      - "feature/*"
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-and-push-image:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Get changed files for Docker build
        id: changed-files-build
        uses: tj-actions/changed-files@v45
        with:
          files: |
            Dockerfile
            requirements.txt

      - name: Set up Docker Buildx
        if: steps.changed-files-build.outputs.any_changed == 'true' || github.event_name == 'workflow_dispatch'
        uses: docker/setup-buildx-action@v3

      - name: Log in to DockerHub
        if: steps.changed-files-build.outputs.any_changed == 'true' || github.event_name == 'workflow_dispatch'
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Build and push Docker image
        if: steps.changed-files-build.outputs.any_changed == 'true' || github.event_name == 'workflow_dispatch'
        run: |
          docker buildx build --push \
            --tag ${{ vars.DOCKERHUB_NAMESPACE }}/${{ vars.DOCKERHUB_REPOSITORY }}:latest \
            --tag ${{ vars.DOCKERHUB_NAMESPACE }}/${{ vars.DOCKERHUB_REPOSITORY }}:${{ github.sha }} \
            .

  unit-and-integration-and-e2e-tests:
    runs-on: ubuntu-latest
    needs: build-and-push-image

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Get changed files for tests
        id: changed-files-tests
        uses: tj-actions/changed-files@v45
        with:
          files: |
            dags/**
            include/**
            tests/**
            docker-compose.yaml
            .github/workflows/cicd_yt_elt.yaml

      - name: Create .env file for Docker Compose
        if: steps.changed-files-tests.outputs.any_changed == 'true' || github.event_name == 'workflow_dispatch'
        run: |
          cat > .env <<EOF
          # Dockerhub Image
          DOCKERHUB_NAMESPACE=${{ vars.DOCKERHUB_NAMESPACE }}
          DOCKERHUB_REPOSITORY=${{ vars.DOCKERHUB_REPOSITORY }}
          IMAGE_TAG=latest

          # Postgres connection
          POSTGRES_CONN_USERNAME=${{ secrets.POSTGRES_CONN_USERNAME }}
          POSTGRES_CONN_PASSWORD=${{ secrets.POSTGRES_CONN_PASSWORD }}
          POSTGRES_CONN_HOST=${{ secrets.POSTGRES_CONN_HOST }}
          POSTGRES_CONN_PORT=${{ secrets.POSTGRES_CONN_PORT }}

          # Metadata database credentials
          METADATA_DATABASE_NAME=${{ secrets.METADATA_DATABASE_NAME }}
          METADATA_DATABASE_USERNAME=${{ secrets.METADATA_DATABASE_USERNAME }}
          METADATA_DATABASE_PASSWORD=${{ secrets.METADATA_DATABASE_PASSWORD }}

          # Celery database credentials
          CELERY_BACKEND_NAME=${{ secrets.CELERY_BACKEND_NAME }}
          CELERY_BACKEND_USERNAME=${{ secrets.CELERY_BACKEND_USERNAME }}
          CELERY_BACKEND_PASSWORD=${{ secrets.CELERY_BACKEND_PASSWORD }}

          # ELT database credentials
          ELT_DATABASE_NAME=${{ secrets.ELT_DATABASE_NAME }}
          ELT_DATABASE_USERNAME=${{ secrets.ELT_DATABASE_USERNAME }}
          ELT_DATABASE_PASSWORD=${{ secrets.ELT_DATABASE_PASSWORD }}

          # Airflow params
          AIRFLOW_UID=${{ vars.AIRFLOW_UID }}
          _AIRFLOW_WWW_USER_USERNAME=${{ secrets.AIRFLOW_WWW_USER_USERNAME }}
          _AIRFLOW_WWW_USER_PASSWORD=${{ secrets.AIRFLOW_WWW_USER_PASSWORD }}
          FERNET_KEY=${{ secrets.FERNET_KEY }}

          # Youtube params
          API_KEY=${{ secrets.API_KEY }}
          CHANNEL_HANDLE=${{ vars.CHANNEL_HANDLE }}
          EOF

      - name: Prepare Airflow folders permissions
        if: steps.changed-files-tests.outputs.any_changed == 'true' || github.event_name == 'workflow_dispatch'
        run: |
          mkdir -p ./dags ./logs ./plugins ./config ./data ./include
          sudo chown -R 50000:0 ./dags ./logs ./plugins ./config ./data ./include
          sudo chmod -R 775 ./dags ./logs ./plugins ./config ./data ./include

      - name: Pull Docker images
        if: steps.changed-files-tests.outputs.any_changed == 'true' || github.event_name == 'workflow_dispatch'
        run: docker compose pull

      - name: Start Docker Compose
        if: steps.changed-files-tests.outputs.any_changed == 'true' || github.event_name == 'workflow_dispatch'
        run: docker compose up -d

      - name: Show running containers
        if: steps.changed-files-tests.outputs.any_changed == 'true' || github.event_name == 'workflow_dispatch'
        run: docker ps -a

      - name: Print Postgres logs if needed
        if: steps.changed-files-tests.outputs.any_changed == 'true' || github.event_name == 'workflow_dispatch'
        run: |
          docker logs postgres || true

      - name: Wait for Airflow services
        if: steps.changed-files-tests.outputs.any_changed == 'true' || github.event_name == 'workflow_dispatch'
        run: |
          echo "Waiting for Airflow services to start..."
          sleep 60
          docker ps -a

      - name: Run Unit and Integration Tests
        if: steps.changed-files-tests.outputs.any_changed == 'true' || github.event_name == 'workflow_dispatch'
        run: |
          docker compose exec -T airflow-worker pytest tests/ -v

      - name: Run End-to-End DAG Tests
        if: steps.changed-files-tests.outputs.any_changed == 'true' || github.event_name == 'workflow_dispatch'
        run: |
          DAG_NAMES=("produce_json" "update_db" "data_quality")

          for DAG in "${DAG_NAMES[@]}"; do
            echo "Testing DAG: $DAG"
            docker compose exec -T airflow-worker airflow dags test "$DAG"
          done

      - name: Print Airflow logs if failed
        if: failure()
        run: |
          echo "===== Docker containers ====="
          docker ps -a || true

          echo "===== Postgres logs ====="
          docker logs postgres || true

          echo "===== Airflow scheduler logs ====="
          docker compose logs airflow-scheduler || true

          echo "===== Airflow dag processor logs ====="
          docker compose logs airflow-dag-processor || true

          echo "===== Airflow worker logs ====="
          docker compose logs airflow-worker || true

          echo "===== Airflow webserver logs ====="
          docker compose logs airflow-webserver || true

      - name: Tear down Docker Compose
        if: always()
        run: docker compose down -v